language: android
android:
  components:
  - android-21
  - build-tools-21.1.2
env:
  global:
  - secure: Dyk2AFOfmpQSRlyEfarfj+NRmBuXLopoUER7mFEv/SJZEyesF2GaeStIimEU/X0RTZfMlU2U0JpI++ZCTKGMhwcROBHpaqGQDXGdAYR8oHpDPKaZbiV5uxNjtncGdCwqAT2XBQA929oHkJHGdVgztHB/57283g9XBm8769r+n50=
  - secure: T0UI6NKNDodAlE6Rn4/jIHDFxZpaXrjtU6sC8qXi6uv/o2GAOnilIMZZCwf5weX0hHmQG9Z0KFAUIiZWzk+mR9bh6Bi+XDSewfLWV1iBRgByFS6HOZBEqWe79ZD9pDyx7KD2V0IG0uIrDzOOGO/D5vvKGyS7HVYzh7c/oGQG2nU=
before_install:
- openssl aes-256-cbc -K $encrypted_c8103935a87e_key -iv $encrypted_c8103935a87e_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- mv madfau.keystore app/
script: "./gradlew assemble"
after_success:
- mv app/build/outputs/apk/app-release.apk kwikshop-android-$TRAVIS_BRANCH-`git rev-parse
  HEAD`.apk
- curl -u $LOGIN -F "apk=@kwikshop-android-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk"
  -F "project=kwikshop-android" $URL
