language: android
android:
  components:
  - android-21
  - build-tools-21.1.2
env:
  global:
  - secure: JrOe+YWYjAlgH4N4YLyORz+TjFmCWZaoyRATAcxm5i6tF9Qfqc4/o16JOilIeZJohi9fyjys4IdNw4m+1jN2jpWMv0gBatL/fMjhpKuHTc1FhOZtze45qBXKOHtqID+ty+BxWCagwAW2k0n4eL0/H7Ht9VA25zivOk+wGl6M/a8=
  - secure: PYl3aW0JbiwDYYeArlgnD9iEBS0Tqn4m4zA2tyB7wQ9dsrYZQNwAcxMurOGnqZQPocXEReyLW4GnjlnnlufvPYouAZhyibVw4S4pqLHmOJgldKQpR9dRdQudUh69ZTiu7aFriU/buOPMdHFVc+sImT5xL6SJ+Z9wsbVFhAM0B2E=
before_install:
- openssl aes-256-cbc -K $encrypted_c8103935a87e_key -iv $encrypted_c8103935a87e_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- mv madfau.keystore app/
script: "./gradlew assemble"
after_success:
- mv app/build/outputs/apk/app-release.apk quickshop-android-$TRAVIS_BRANCH-`git rev-parse
  HEAD`.apk
- curl -u $LOGIN -F "apk=@quickshop-android-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk"
  -F "project=quickshop-android" $URL
