language: android
android:
  components:
  - extra-google-google_play_services
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository  
  - android-21
  - build-tools-21.1.2
env:
  global:
  - secure: db7JC1TqNV+WYPwBi/Ax6cbrGC6Eq0cVU3kZKTj0cGD8E3gEKGD9yt0fqKWvj1VGg7WxbBysxlJyiQOPRtuRTI4lVA5BFyga1Dj3DLPkDEcjUbYDbSsyTBwDO5f248qdP9WlCoEUhIgXlqHKbWMFFG06ORjov2ZceJOkFGKe0cNz42YcG7NXmMszOpTylkneSD2GlbTU8s7izpgbUHjR9hzhm/CxikgXhqOKXjlvDnFAfxITaPkmDcB4Od34y1+wVAX+eqwttyJ0jVEAAcLYvmsleeClexyJ4DJfi0cbbEmMPDGNiNpUg2W29EFh/OK8oKaHY+onzidBUzXfgHjXoRKLPkaT/ncZE9oMrS+fSbjXsMKaBxA/iIFZ4kky+zRr1G/0LATXpt9p5SFAi+gCoDW5O+Z7OwYcECYt7lS8R4vGRu4XznFUMkx4uubE3Lm18vsLqEBrxbI3M8IS0EUKQxUGcTWXqqioz4avqvdFfCY77kKnMHS3gorBJKCQQZGCjKaELTRSGiW/rOutvswEBYRSpJMiLec1Wjmk6GRs+6aLU+rzUfzj2jx/njE8lUmmrpkW6khBKuwmhR1HS27akMfWmmeLvEQ8kxQn3kYmdR/9p46qckDo/OILIwLytNjTAIvFBQqNda8kEL0r/sPiii2VrpIr4OHYf+aqCPcXyVA=
  - secure: UFYntpjaLsdvziLsGHgdcWsUFJappoSIKVCyojaCizRZGO0aMua+GRno6sDwb3LYZ9UTJbvinkY7gwLYkBjW1p+UjLEQwRUCFLmBY0ROfx7CMZE3BLPGemEOO3wOUT4SX7Sl/ztjK63hRh4+ekTyaOYIvvMOHBaE6ZYAOtRdo9K88JECh7FrCmblfwKa6ZofoWRV63TlUReeNFQ/O1i6mygE/yQjuMSqMk1LmY/1clwiRN+Z3xEyvKb8KjdDG+Z89rE3H5YEOo69zvV03Vq2p9VXWQ+F65Ojbk5c6I9uIKPXs310gpaIbVa7S8CfYtdVtnnGiYXkLAGCH9jfKMMfZh9WbQM6rP2HDv+RlaYItZY5CNsc1aRthzRZd1iznRK5Ol3YiNAGcc/qrPAULbboyqvjNoXRR5+gGpqCtPKk1/ns6SPWONVFHQIq1xejqotq1N4Ev8uTfERAsR5DCU2kEhoJBpiGAPVUVyLIBp5LKqgiqd5mLTZkJQhXfOVseihgT9rjDPddKho66BC3/22VrLSnL4DB5iekEuYyxzxFXRMONCpyLkECHk4pGV6T8EjR3awyG3scXR0xrT6EO2W5WG4ipY3dDLSGFYAuEPQIzY3lUYuIq5GZ29AoET5PaRZzdEkQxJHXOEY2BYfqTh3Ayt033pWtNNm1q+150UcCMHc=
before_install:
- openssl aes-256-cbc -K $encrypted_40ff18429069_key -iv $encrypted_40ff18429069_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- mv madfau.keystore app/
script: "./gradlew assemble"
after_success:
- mv app/build/outputs/apk/app-release.apk kwikshop-android-$TRAVIS_BRANCH-`git rev-parse
  HEAD`.apk
- curl -u $LOGIN -F "apk=@kwikshop-android-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk"
  -F "project=kwikshop-android" $URL
