package de.fau.cs.mad.kwikshop.android.common;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "autoCompletionBrandData")
public class AutoCompletionBrandData{
    /**
     * unique id generated by storage
     */
    @DatabaseField(generatedId = true)
    private int id;

    /**
     * the brand name that was entered by a user
     */
    @DatabaseField(canBeNull = false)
    private String brand;


    public AutoCompletionBrandData() {
        // Default no-arg constructor for generating Groups, required for ORMLite
    }

    public AutoCompletionBrandData(String brand) {
        this.brand = brand;
    }

    public int getId() {
        return id;
    }

    public String getName(){
        return brand;
    }
}
