package de.cs.fau.mad.quickshop.android;

import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.Vector;

public class ShoppingList {

  /** 
   *  unique id generated by storage
   */
  private int id;

  /**
   *  not unique, can be set by user
   */
  private String name;

  /**
   * Date of an Event for Calendar Usage
   */
  private CalendarEventDate eventDate = new CalendarEventDate();

  /**
   * type: Account.id
   */

  private Vector<Integer> sharedWith;

  private LinkedList<Item> items = new LinkedList<>(); // TODO: different data type?

  private ListStorage storage;
  private Account owner;

  private enum visibility {
    PRIVATE
  }
  private visibility vis;


  public ShoppingList(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public CalendarEventDate getCalendarEventDate() {return eventDate; }

  public void setCalendarEventDate(CalendarEventDate eventDate){this.eventDate = eventDate; }

  public Vector getSharedWith() {
    return sharedWith;
  }

  public visibility getVisibility() {
    return vis;
  }

  public void setVisibility(visibility visibility) {
    this.vis = visibility;
  }

  public Boolean save() {
    return storage.saveList(this);
  }

  public Boolean delete() {
    return storage.deleteList(this.getId());
  }

  public void addItem(Item item) {
    this.items.add(item);
  }

  public void removeItem(int id) {
    ListIterator<Item> listIterator = items.listIterator();

    while (listIterator.hasNext()) {
      Item currentItem = listIterator.next();
      if(currentItem.getId() == id) {
        items.remove(currentItem);
        return;
      }
    }
  }


  public Collection<Item> getItems() {
    return Collections.unmodifiableCollection(this.items);
  }

}
